#!/usr/bin/env bash

test_description='cli'

. lib/test-lib.sh

################################################################

test_expect_code 5 'dump non-existant db' \
    'assword dump'

test_expect_success 'add first entry' \
    'assword add foo@bar'

test_expect_success 'add second entry' \
    "assword add 'baz asdf Dokw okb 32438uoijdf'"

test_expect_code 2 'add existing context' \
    'assword add foo@bar'

test_begin_subtest "dump all entries"
assword dump 2>&1 | sed 's/"date": ".*"/FOO/g' >OUTPUT
cat <<EOF >EXPECTED
{
  "baz asdf Dokw okb 32438uoijdf": {
    FOO
  },
  "foo@bar": {
    FOO
  }
}
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest "dump search 0"
assword dump foo 2>&1 | sed 's/"date": ".*"/FOO/g' >OUTPUT
cat <<EOF >EXPECTED
{
  "foo@bar": {
    FOO
  }
}
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest "dump search 1"
assword dump asdf 2>&1 | sed 's/"date": ".*"/FOO/g' >OUTPUT
cat <<EOF >EXPECTED
{
  "baz asdf Dokw okb 32438uoijdf": {
    FOO
  }
}
EOF
test_expect_equal_file OUTPUT EXPECTED

test_begin_subtest "dump search 2"
assword dump ba 2>&1 | sed 's/"date": ".*"/FOO/g' >OUTPUT
cat <<EOF >EXPECTED
{
  "baz asdf Dokw okb 32438uoijdf": {
    FOO
  },
  "foo@bar": {
    FOO
  }
}
EOF
test_expect_equal_file OUTPUT EXPECTED

test_expect_code 2 'add existing context' 'assword add foo@bar'
test_expect_code 2 'replace non-existing context' \
    'assword replace aaaa'


test_expect_code 2 'remove non-existant entry' 'assword remove aaaa'

test_begin_subtest "remove entry"
echo yes | assword remove foo@bar
assword dump 2>&1 | sed 's/"date": ".*"/FOO/g' >OUTPUT
cat <<EOF >EXPECTED
{
  "baz asdf Dokw okb 32438uoijdf": {
    FOO
  }
}
EOF
test_expect_equal_file OUTPUT EXPECTED

################################################################

test_done
